In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [2]:
df=pd.read_csv('grades_data.csv',dtype={'english':int,'maths':int,'grade':int})
print(df.dtypes)

english    int32
maths      int32
grade      int32
dtype: object


In [3]:
x1=np.array(df['english'])
x2=np.array(df['maths'])
X=np.stack((x1,x2),axis=1)
X

array([[67, 91],
       [34, 79],
       [76, 61],
       [54, 55],
       [98, 86],
       [49, 73],
       [77, 24],
       [61, 10],
       [32, 67],
       [87, 51],
       [63, 43],
       [39, 39],
       [43, 16],
       [55, 97],
       [18, 81],
       [ 8, 36],
       [90,  3],
       [57, 77],
       [71, 61],
       [99, 83]])

In [4]:
y=np.array(df['grade'])
y

array([2, 3, 2, 3, 1, 2, 3, 4, 3, 2, 3, 4, 4, 2, 3, 4, 3, 2, 2, 1])

In [5]:
layer1=Dense(10,activation='relu',name="layer1")
layer2=Dense(10,activation='relu',name="layer2")
layer3=Dense(5,activation='softmax',name="layer3")

In [6]:
model=Sequential([layer1,layer2,layer3])

In [7]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy')

In [8]:
model.fit(X,y,epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 42.6492
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 42.0690
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 41.4926
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 40.9209
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 40.3617
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 39.8083
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 39.2589
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 38.7204
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 38.1994
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 37.6886


In [13]:
inp=np.array([[92,43],[11,77]])
ans=model.predict(inp)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


In [14]:
ans

array([[1.7824506e-20, 1.5526912e-33, 3.6790218e-22, 1.0000000e+00,
        2.9099162e-35],
       [6.1380359e-11, 9.7830654e-27, 3.2070377e-16, 1.0000000e+00,
        6.8572193e-35]], dtype=float32)

In [18]:
cls=np.argmax(ans,axis=1)

In [19]:
cls

array([3, 3], dtype=int64)