In [1]:
import math
import numpy as np
import pandas as pd

In [2]:
dict={"Size":[1906,2114,1532,1171,2273,1294,1732],"Floors":[2,2,2,3,1,3,1],"Age":[20,25,29,34,19,36,29],"Rooms":[4,6,4,5,4,3,3],"Cost":[110,140,95,150,120,160,100]}
df=pd.DataFrame(dict)
df

Size  Floors  Age  Rooms  Cost
0  1906       2   20      4   110
1  2114       2   25      6   140
2  1532       2   29      4    95
3  1171       3   34      5   150
4  2273       1   19      4   120
5  1294       3   36      3   160
6  1732       1   29      3   100

In [3]:

y=np.array(df['Cost'])
df2=df.drop('Cost',axis=1)
x=df2.to_numpy()

y,x

(array([110, 140,  95, 150, 120, 160, 100], dtype=int64),
 array([[1906,    2,   20,    4],
        [2114,    2,   25,    6],
        [1532,    2,   29,    4],
        [1171,    3,   34,    5],
        [2273,    1,   19,    4],
        [1294,    3,   36,    3],
        [1732,    1,   29,    3]], dtype=int64))

In [4]:
def compute_cost(x,y,w,b):
    m,n=x.shape
    dj_dw=np.zeros(n)
    dj_db=0

    for i in range(m):
        err=(np.dot(x[i],w)+b)-y[i]
        for j in range(n):
            dj_dw[j]=dj_dw[j]+err*x[i,j]
        dj_db=dj_db+err
    dj_dw=dj_dw/m
    dj_bb=dj_db/m

    return dj_dw,dj_db

In [5]:
def gradient_descent(w,b,alpha):
    for i in range(1000):
        dj_dw,dj_db=compute_cost(x,y,w,b)
        w=w-alpha*dj_dw
        b=b-alpha*dj_db
    return w,b

In [6]:
w_init=np.zeros(x.shape[1])
b_init=0
alpha=5.0e-7
w,b=gradient_descent(w_init,b_init,alpha)
w,b

(array([0.06525752, 0.02108508, 0.20537432, 0.01565187]), 0.026196098709441947)

In [7]:
print("Estimate price for house :-")
f1=int(input("Size"))
f2=int(input("Floors"))
f3=int(input("Age"))
f4=int(input("Rooms"))
f=[f1,f2,f3,f4]
print(f"Cost of the House is {np.dot(w,f)+b}")

Estimate price for house :-


Size 2100
Floors 3
Age 20
Rooms 6


Cost of the House is 141.33164552264617
